### PR TITLE
Add CI

### PR DESCRIPTION
**Pull request by HKalbasi**
This PR adds CI which checks tests, format and compiler errors and warnings. I ignored the failing test for now since you said you want to rewrite them. I also commit the Cargo.lock file, it would guarantee that ox build successfully if someone clone it (without Cargo.lock dependencies can accidentally create problems).

### CODE REVIEW

**Comment by curlpipe** [comment]
Great, so I've rewritten the tests (and removed the unnecessarily huge test files)

**Comment by curlpipe** [comment]
(Let me know if you are happy to merge)

**Comment by HKalbasi** [comment]
I'm happy to merge

**Comment by curlpipe** [comment]
Let's do it!

**Comment by curlpipe** [comment]
By the way @HKalbasi, would you be up for me adding your name to the README? (under the Acknowledgements section)

**Comment by HKalbasi** [comment]
It would be nice, thanks

**Pull request merged**
