### PR TITLE
chore: Replace quick_error with error_set

### PR DESCRIPTION
**Pull request by mcmah309**
I was looking at your code and saw that you used `quick_error`, which I hadn't heard of. I've been working on another error definition approach [error_set](https://github.com/mcmah309/error_set) and I wanted to see if there were any features in `quick_error` it was missing or I could get inspiration from. So I replaced `quick_error` with `error_set` to see. Looks like it covers all the features.

Feel free to not merge and close this PR if you prefer the ergonomics of `quick_error`.

### CODE REVIEW

**Comment by mcmah309** [comment]
Something I noticed by the way, you may have intended this, but with `quick_error` it seems you can easily for get to delegate source correctly. If not intended, `source(err)` should have been added here https://github.com/curlpipe/ox/blob/bb2192a8d526c32de784836ec1e3affb38d0bf92/src/error.rs#L12 like it is here https://github.com/curlpipe/ox/blob/bb2192a8d526c32de784836ec1e3affb38d0bf92/kaolinite/src/event.rs#L90
  - `quick_error`: `OxError::Render(ref err) => None,`
  - `error_set`: `OxError::Render(ref source) => source.source(),` (handled correctly)

**Comment by curlpipe** [comment]
Thank you for the PR, I really like the syntax of your `error_set` library, it feels much more compact and readable than `quick_error`. The only concern I have is that it increases the build time and number of dependencies. I've never had much of a problem with `quick_error`, so I'm hesitant to make the switch. I would love to use `error_set` if there was some way it could be made lighter.

As for the `source(err)`, that's a good catch. The code I wrote here is quite old (2-4 years old) so I can't fully remember what I intended. Either way, it's probably best to include `source` here. Thanks for bringing that to my attention.

**Comment by mcmah309** [comment]
Glad to hear you like it!

`error_set` is a proc macro and has no other dependencies (unless you want to enable a feature flag like `tracing`). Proc macros are all compiled beforehand, then the executable is executed by the rust compiler at build time, and since it is replacing `quick_error`, the number of dependencies will not change.

I'd be surprised if it increased the build time. Are you seeing that locally?

Either or, totally fine if you prefer the previous way. Always open to some suggestions on the API as well.

**Comment by curlpipe** [comment]
Yes, I tested it locally. I'll keep an eye on `error_set` and keep this PR open because I am totally open to using it. :+1:

**Comment by mcmah309** [comment]
I had some time today to look into the build time increase issue you mentioned and was unable to reproduce it. Is this what you are seeing as well?

### Clean build
Command:
```bash
hyperfine --prepare "cargo clean" "cargo build"
```
#### Before Changes
```console
Benchmark 1: cargo build
  Time (mean ± σ):     16.851 s ±  0.251 s    [User: 43.940 s, System: 8.691 s]
  Range (min … max):   16.604 s … 17.512 s    10 runs
```
#### After Changes
```console
Benchmark 1: cargo build
  Time (mean ± σ):     16.857 s ±  0.163 s    [User: 49.649 s, System: 9.791 s]
  Range (min … max):   16.628 s … 17.218 s    10 runs
```

### Incremental build
Command:
```bash
hyperfine --prepare 'echo -e "\nfn T$(date +"%s")(){}" >> src/main.rs' "cargo build"
```

#### Before Changes
```console
Benchmark 1: cargo build
  Time (mean ± σ):     888.3 ms ±  22.9 ms    [User: 832.3 ms, System: 713.2 ms]
  Range (min … max):   863.5 ms … 931.5 ms    10 runs
```

#### After Changes
```console
Benchmark 1: cargo build
  Time (mean ± σ):     903.8 ms ±  15.8 ms    [User: 827.6 ms, System: 739.6 ms]
  Range (min … max):   880.5 ms … 931.5 ms    10 runs
```

**Comment by curlpipe** [comment]
Ah yeah, you're right. Perhaps I just ended up being unlucky in my tests (I didn't test them more than once, so it might have just been a coincidence).

**Comment by curlpipe** [comment]
Alright, I think it's good to go.

After merge, it'll sit in the 0.6.10 branch until about next week when the 0.6.10 update is completed and published :+1:

**Pull request merged**
