### PR TITLE
Add Homebrew install instructions to readme

### PR DESCRIPTION
**Pull request by vladimyr**
`ox` has been added to Homebrew https://github.com/Homebrew/homebrew-core/pull/63915 :tada:

### CODE REVIEW

**Comment by curlpipe** [comment]
Brilliant!
Thank you :)

**Comment by curlpipe** [comment]
@vladimyr Is there any chance you could transfer ownership to me so that I can keep it up to date? Many thanks

**Comment by vladimyr** [comment]
> @vladimyr Is there any chance you could transfer ownership to me so that I can keep it up to date? Many thanks 

What do you mean by _ownership_? I don't own it everyone could do PR updating it 🤔

**Comment by vladimyr** [comment]
You may find it useful https://github.com/mislav/bump-homebrew-formula-action 😉

**Pull request merged**
