### PR TITLE
Include kaolinite in the tree

### PR DESCRIPTION
**Pull request by HKalbasi**
This is on top of #135. I will make it a draft until that one is merged.

### CODE REVIEW

**Comment by HKalbasi** [comment]
`991,760` lines of diff doesn't look natural. I think I messed up something.

**Comment by HKalbasi** [comment]
Ah, it's the `demos/9.txt` file. So I guess everything was ok.

**Comment by curlpipe** [comment]
Yeah, that's just a super long file for testing purposes

**Comment by curlpipe** [comment]
(due to some changes in kaolinite, I've done this slightly differently)
Kaolinite and Ox are in a monorepo as of 0.5.0

**Comment by HKalbasi** [comment]
All great! I will make up a selection PR soon™.

**Pull request closed without merging**
